# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slide', models.CharField(max_length=100, null=True)),
                ('slide_url', models.CharField(max_length=10, null=True)),
                ('reading', models.CharField(max_length=100, null=True)),
                ('reading_url', models.CharField(max_length=100, null=True)),
                ('events', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
