# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171116_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='events',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='reading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='reading_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='slide',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='slide_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
