# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171116_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='classperiod',
            name='events_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
