# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_classperiod_events_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='slide',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
