# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-16 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171116_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='classperiod',
            old_name='slide',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='classperiod',
            old_name='events',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='classperiod',
            name='events_url',
        ),
        migrations.RemoveField(
            model_name='classperiod',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='classperiod',
            name='reading_url',
        ),
        migrations.RemoveField(
            model_name='classperiod',
            name='slide_url',
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AddField(
            model_name='readings',
            name='classperiod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ClassPeriod'),
        ),
        migrations.AddField(
            model_name='events',
            name='classperiod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ClassPeriod'),
        ),
    ]
