# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-16 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171116_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Readings',
            new_name='Reading',
        ),
    ]
