# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-16 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171116_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
