# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-16 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171116_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classperiod',
            options={'ordering': ['-date']},
        ),
    ]
