# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-16 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171116_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classperiod',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='classperiod',
            new_name='class_period',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='classperiod',
            new_name='class_period',
        ),
    ]
